### PR TITLE
Task 3

### PR DESCRIPTION
**Pull request by Rakymzhan**

### CODE REVIEW

**Comment by bodik777** [comment]
Hi, did you go through evaluation criteria of the task?

- Correctly modified the application.properties file to change the deployment name for different models (15%)
- Successfully retrieved deployment names using the provided API (15%)
- Correctly implemented the logic to switch between different models based on the deployment name (15%)
- Ensured that the application can call different models from the Dial service (15%)
- Compared results for the same prompts using different models (10%)
- Compared results using different PromptExecutionSettings (10%)
- Documented observations and differences in the results (10%)
- Application runs without errors (5%)
- Responses are generated correctly and are relevant to the prompts (5%)

I am not able to execute any prompt successfully

**Comment by Rakymzhan** [comment]
Hi,
I will check

**Comment by Rakymzhan** [comment]
Hi,
Actually, regarding first criteria, we need just remove 'client-azureopenai-deployment-name' from application.properties as we retrieve modelIds from EPAM's endpoint.
Also, not all models will return result for 'I want to find top-10 books about world history', for example DALL-E.

Therefore, I just wanted to send predefined modelIds in requests together with prompt, this would be more dynamic then constants

**Comment by Rakymzhan** [comment]
Also, regarding this criteria 'Successfully retrieved deployment names using the provided API (15%)', what for we need to do this if we can use predefined modelIds, I really did not understand.

image

**Comment by Rakymzhan** [comment]
Anyway, thank you for reviewing, I will fix some stuff there

**Comment by Rakymzhan** [comment]
Hi Bohdan,

I have just pushed new changes. Now this works somehow)).
Please, look into README file for observations and some instructions to run it.
Checked locally, every response from every model has comparisons with other models.

Response looks like this:

image

**Comment by Rakymzhan** [comment]
Please, review it

**Comment by bodik777** [comment]
now it looks much better!

**Pull request merged**
